# StackRox Google Function scan sample
# author neil@stackrox.com

version: 2.1
jobs:
  scan:
    docker:
      - image: cimg/base:2020.10
    steps:
      - run: |
          ROX_RETURN=$(curl -L -H "Authorization: Bearer $goog_api_token" https://<<project>>.cloudfunctions.net/roxctl_image_check \
            --silent --fail --show-error \
            --header "Content-Type: application/json" \
            --request POST \
            --data "{\"rox_central_endpoint\": \"$ROX_CENTRAL_ENDPOINT\",\"rox_api_token\": \"$rox_api_token\",\"rox_image\": \"mysql:5.6.30\"}")
          echo $ROX_RETURN | jq --raw-output '.output'
          [ "$(echo $ROX_RETURN | jq --raw-output '.build')" == "fail" ] && exit 1
# This uses cURL to execute the Google Cloud Function.  The function returns JSON with pass/fail and the output.
# We echo the output and, finally, if the result is fail, exit with a non-zero return code to fail the build        

workflows:
  scanimage:
    when: always
    jobs:
      - scan:
          name: scan